run:
  deadline: 20m
  go-version: "1.23"

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true

issues:
  # default: 50
  max-issues-per-linter: 0
  exclude-rules:
    - text: "unused-parameter: parameter '.*' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive

linters-settings:
  goimports:
    local-prefixes: github.com/Azure/azure-workload-identity
