run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks
  fast: true
