version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter ''.*'' seems to be unused, consider removing or renaming it as _'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/Azure/azure-workload-identity
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
