run:
  deadline: 20m
  # some of the linters don't work correctly with 1.18
  # xref: https://github.com/golangci/golangci-lint/issues/2649
  # we are not using generics, so we can pin this to 1.17
  go: '1.17'

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true
