run:
  deadline: 20m
  go-version: "1.20"

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks
  fast: true

linters-settings:
  goimports:
    local-prefixes: github.com/Azure/azure-workload-identity
