# refer to https://goreleaser.com for more options
before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  - id: azwi
    dir: cmd/azwi
    binary: azwi
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -mod=vendor
    ldflags:
      - -s
      - -w
      - -X {{.ModulePath}}/pkg/version.BuildTime={{.Date}}
      - -X {{.ModulePath}}/pkg/version.BuildVersion={{.Tag}}
      - -X {{.ModulePath}}/pkg/version.Vcs={{.ShortCommit}}
release:
  prerelease: auto
  header: |
    ## {{.Tag}} - {{ time "2006-01-02" }}
  extra_files:
    - glob: deploy/*.yaml
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "azwi-{{.Tag}}-{{.Os}}-{{.Arch}}"
checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256
changelog:
  skip: false
  groups:
    - title: Bug Fixes 🐞
      regexp: ^.*fix[(\\w)]*:+.*$
    - title: Build 🏭
      regexp: ^.*build[(\\w)]*:+.*$
    - title: Code Refactoring 💎
      regexp: ^.*refactor[(\\w)]*:+.*$
    - title: Code Style 🎶
      regexp: ^.*style[(\\w)]*:+.*$
    - title: Continuous Integration 💜
      regexp: ^.*ci[(\\w)]*:+.*$
    - title: Documentation 📘
      regexp: ^.*docs[(\\w)]*:+.*$
    - title: Features 🌈
      regexp: ^.*feat[(\\w)]*:+.*$
    - title: Maintenance 🔧
      regexp: ^.*chore[(\\w)]*:+.*$
    - title: Performance Improvements 🚀
      regexp: ^.*perf[(\\w)]*:+.*$
    - title: Revert Change ◀️
      regexp: ^.*revert[(\\w)]*:+.*$
    - title: Security Fix 🛡️
      regexp: ^.*security[(\\w)]*:+.*$
    - title: Testing 💚
      regexp: ^.*test[(\\w)]*:+.*$
