apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: aad-pi-webhook-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "aad-pi-webhook-webhook-service.{{ .Release.Namespace }}.svc"
  - "aad-pi-webhook-webhook-service.{{ .Release.Namespace }}.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: aad-pi-webhook-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: aad-pi-webhook-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
