apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    {{- toYaml .Values.mutatingWebhook.annotations | nindent 4 }}
  name: aad-pi-webhook-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  name: mpod.aad-pod-identity.io
  clientConfig:
    service:
      name: aad-pi-webhook-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
  failurePolicy: Ignore
  matchPolicy: Equivalent
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
  sideEffects: None