[book]
authors = ["Ernest Wong"]
language = "en"
multilingual = false
src = "src"
title = "AAD Pod Managed Identity"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/Azure/azure-workload-identity"

[preprocessor.toc]
command = "bin/mdbook-toc"
