apiVersion: v1
kind: Service
metadata:
  labels:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-wi-webhook-webhook-service
  namespace: '{{ .Release.Namespace }}'
spec:
  {{- if .Values.service }}
  type: {{  .Values.service.type | default "ClusterIP" }}
  {{- end }}
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
