apiVersion: v1
kind: Namespace
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-admin
  namespace: aad-pi-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-manager-role
  namespace: aad-pi-webhook-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-manager-rolebinding
  namespace: aad-pi-webhook-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aad-pi-webhook-manager-role
subjects:
- kind: ServiceAccount
  name: aad-pi-webhook-admin
  namespace: aad-pi-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aad-pi-webhook-manager-role
subjects:
- kind: ServiceAccount
  name: aad-pi-webhook-admin
  namespace: aad-pi-webhook-system
---
apiVersion: v1
data:
  AZURE_ENVIRONMENT: <replace with Azure Environment Name>
  AZURE_TENANT_ID: <replace with Azure Tenant ID>
kind: ConfigMap
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-config
  namespace: aad-pi-webhook-system
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-server-cert
  namespace: aad-pi-webhook-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-webhook-service
  namespace: aad-pi-webhook-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    mpod.aad-pod-identity.io/system: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-controller-manager
  namespace: aad-pi-webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      mpod.aad-pod-identity.io/system: "true"
  template:
    metadata:
      labels:
        mpod.aad-pod-identity.io/system: "true"
    spec:
      containers:
      - args:
        - --arc-cluster=false
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: aad-pi-webhook-config
        image: mcr.microsoft.com/oss/azure/aad-pod-managed-identity/webhook:v0.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: healthz
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /certs
          name: cert
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: aad-pi-webhook-admin
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: aad-pi-webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    mpod.aad-pod-identity.io/system: "true"
  name: aad-pi-webhook-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: aad-pi-webhook-webhook-service
      namespace: aad-pi-webhook-system
      path: /mutate-v1-pod
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: mpod.aad-pod-identity.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
