parameters:
  - name: dependsOn
    type: object
  - name: matrix
    type: object

jobs:
  - job:
    timeoutInMinutes: 90
    dependsOn: ${{ parameters.dependsOn }}
    workspace:
      clean: all
    variables:
      # contains the following environment variables:
      # - APPLICATION_CLIENT_ID
      # - AZURE_TENANT_ID
      # - KEYVAULT_NAME
      # - KEYVAULT_SECRET_NAME
      - group: e2e-environment-variables-update
      - name: REGISTRY
        value: upstream.azurecr.io/azure-workload-identity
    strategy:
      matrix: ${{ parameters.matrix }}
    steps:
      - script: echo "##vso[task.setvariable variable=CLUSTER_NAME]azwi-e2e-$(openssl rand -hex 2)"
        displayName: Set CLUSTER_NAME
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          SKIP_CLEANUP: "true"
          APPLICATION_CLIENT_ID: $(APPLICATION_CLIENT_ID)
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          KEYVAULT_NAME: $(KEYVAULT_NAME)
          KEYVAULT_SECRET_NAME: $(KEYVAULT_SECRET_NAME)
      - script: |
          # xref: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/512316adc9daa2216de10a6288f6c1df8a122654/.pipelines/templates/aks-upgrade.yaml#L3-L8
          MINOR_VERSION="$(az aks get-upgrades --resource-group ${CLUSTER_NAME} --name ${CLUSTER_NAME} --query "controlPlaneProfile.kubernetesVersion" | jq -r 'split(".") | .[:2] | join(".")')"
          echo "Minor version is - ${MINOR_VERSION}"
          UPGRADE_VERSION="$(az aks get-upgrades --resource-group ${CLUSTER_NAME} --name ${CLUSTER_NAME} --query "max(controlPlaneProfile.upgrades[?isPreview==null && !(starts_with(kubernetesVersion, '${MINOR_VERSION}'))].kubernetesVersion)" -otsv)"
          echo "Upgrading to Kubernetes ${UPGRADE_VERSION}"

          az aks upgrade --resource-group "${CLUSTER_NAME}" --name "${CLUSTER_NAME}" --kubernetes-version "${UPGRADE_VERSION}" --yes > /dev/null
        displayName: Upgrade cluster
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          APPLICATION_CLIENT_ID: $(APPLICATION_CLIENT_ID)
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          KEYVAULT_NAME: $(KEYVAULT_NAME)
          KEYVAULT_SECRET_NAME: $(KEYVAULT_SECRET_NAME)
      - script: az group delete --name "${CLUSTER_NAME}" --yes --no-wait || true
        displayName: Cleanup
        condition: always()
      - template: publish-logs.yaml
