apiVersion: v1
kind: Pod
metadata:
  name: httpbin-pod
  labels:
    app: httpbin
spec:
  serviceAccountName: old-sa
  initContainers:
  - name: init-networking
    image: docker.pkg.github.com/azure/aad-pod-managed-identity/proxy-init:latest
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: proxy
    image: docker.pkg.github.com/azure/aad-pod-managed-identity/proxy:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
