apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '{{ template "pod-identity-webhook.name" . }}'
    chart: '{{ template "pod-identity-webhook.name" . }}'
    mpod.aad-pod-identity.io/system: "true"
    release: '{{ .Release.Name }}'
  name: aad-pi-webhook-controller-manager
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: '{{ template "pod-identity-webhook.name" . }}'
      chart: '{{ template "pod-identity-webhook.name" . }}'
      mpod.aad-pod-identity.io/system: "true"
      release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app: '{{ template "pod-identity-webhook.name" . }}'
        chart: '{{ template "pod-identity-webhook.name" . }}'
        mpod.aad-pod-identity.io/system: "true"
        release: '{{ .Release.Name }}'
    spec:
      containers:
      - args:
        - -arc-cluster={{ .Values.arcCluster }}
        command:
        - /manager
        envFrom:
        - configMapRef:
            name: aad-pi-webhook-config
        image: '{{ .Values.image.repository }}:{{ .Values.image.release }}'
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
