apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: '{{ template "pod-identity-webhook.name" . }}'
    chart: '{{ template "pod-identity-webhook.name" . }}'
    mpod.aad-pod-identity.io/system: "true"
    release: '{{ .Release.Name }}'
  name: aad-pi-webhook-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
