apiVersion: v1
data:
  AZURE_ENVIRONMENT: {{ .Values.azureEnvironment | default "AzurePublicCloud" }}
  AZURE_TENANT_ID: {{ required "A valid .Values.azureTenantID entry required!" .Values.azureTenantID }}
  {{- if .Values.customTokenEndpoint.azureKubernetesCaData }}
  AZURE_KUBERNETES_CA_DATA: {{ .Values.customTokenEndpoint.azureKubernetesCaData | quote }}
  {{- end }}
  {{- if .Values.customTokenEndpoint.azureKubernetesSniName }}
  AZURE_KUBERNETES_SNI_NAME: {{ .Values.customTokenEndpoint.azureKubernetesSniName | quote }}
  {{- end }}
  {{- if .Values.customTokenEndpoint.azureKubernetesTokenEndpoint }}
  AZURE_KUBERNETES_TOKEN_PROXY: {{ .Values.customTokenEndpoint.azureKubernetesTokenEndpoint | quote }}
  {{- end }}
  {{- if .Values.customTokenEndpoint.azureKubernetesCAConfigMapName }}
  AZURE_KUBERNETES_CA_CONFIGMAP_NAME: {{ .Values.customTokenEndpoint.azureKubernetesCAConfigMapName | quote }}
  {{- end }}
  {{- if .Values.customTokenEndpoint.azureKubernetesCACTBSignerName }}
  AZURE_KUBERNETES_CA_CTB_SIGNER_NAME: {{ .Values.customTokenEndpoint.azureKubernetesCACTBSignerName | quote }}
  {{- end }}
  {{- if .Values.customTokenEndpoint.azureKubernetesCACTBLabelSelector }}
  AZURE_KUBERNETES_CA_CTB_LABEL_SELECTOR: {{ .Values.customTokenEndpoint.azureKubernetesCACTBLabelSelector | quote }}
  {{- end }}
kind: ConfigMap
metadata:
  labels:
    app: '{{ template "workload-identity-webhook.name" . }}'
    azure-workload-identity.io/system: "true"
    chart: '{{ template "workload-identity-webhook.name" . }}'
    release: '{{ .Release.Name }}'
  name: azure-wi-webhook-config
  namespace: '{{ .Release.Namespace }}'
