# ref: https://github.com/Azure/aks-engine/blob/master/.chglog/config.yml
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Azure/azure-workload-identity
options:
  commits:
    filters:
      Type:
        - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - security
        - test
    sort_by: Scope
  commit_groups:
    title_maps:
      build: Build 🏭
      chore: Maintenance 🔧
      ci: Continuous Integration 💜
      docs: Documentation 📘
      feat: Features 🌈
      fix: Bug Fixes 🐞
      perf: Performance Improvements 🚀
      refactor: Code Refactoring 💎
      revert: Revert Change ◀️
      security: Security Fix 🛡️
      style: Code Style 🎶
      test: Testing 💚
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
