trigger: none

pr: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Test"
    branches:
      include:
        - main

pool: staging-pool-amd64-mariner-2

jobs:
  - job:
    timeoutInMinutes: 60
    workspace:
      clean: all
    variables:
      # contains the following environment variables:
      # - APPLICATION_CLIENT_ID
      # - AZURE_TENANT_ID
      # - KEYVAULT_URL
      # - KEYVAULT_SECRET_NAME
      - group: e2e-environment-variables
      - name: REGISTRY
        value: upstream.azurecr.io/azure-workload-identity
      - name: SOAK_CLUSTER
        value: "true"
    strategy:
      matrix:
        soak_aks_windows:
          WINDOWS_CLUSTER: "true"
          GINKGO_SKIP: \[LinuxOnly\]
          CLUSTER_NAME: "azwi-aks-win-containerd"
        soak_aks_linux:
          CLUSTER_NAME: "azwi-aks-linux"
    steps:
      - task: GoTool@0
        inputs:
          version: "1.24.6"
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          APPLICATION_CLIENT_ID: $(APPLICATION_CLIENT_ID)
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          KEYVAULT_URL: $(KEYVAULT_URL)
          KEYVAULT_SECRET_NAME: $(KEYVAULT_SECRET_NAME)
      - template: templates/publish-logs.yaml
  - template: templates/upgrade.yaml
    parameters:
      matrix:
        upgrade_aks_windows:
          WINDOWS_CLUSTER: "true"
          GINKGO_SKIP: \[AKSSoakOnly\]
        upgrade_aks_linux:
          GINKGO_SKIP: \[AKSSoakOnly\]
  - job:
    pool:
      name: staging-pool-amd64-mariner-2
      demands:
      - ImageOverride -equals azcu-agent-amd64-mariner-2-cgv2-img
    timeoutInMinutes: 60
    workspace:
      clean: all
    variables:
      # contains the following environment variables:
      # - APPLICATION_CLIENT_ID
      # - AZURE_TENANT_ID
      # - KEYVAULT_URL
      # - KEYVAULT_SECRET_NAME
      # - SERVICE_ACCOUNT_ISSUER
      # - SERVICE_ACCOUNT_KEYVAULT_NAME
      - group: e2e-environment-variables
      - name: LOCAL_ONLY
        value: "true"
      - name: TEST_HELM_CHART
        value: "true"
    strategy:
      matrix:
        kind_v1_30_10:
          KIND_NODE_VERSION: v1.30.10
        kind_v1_31_6:
          KIND_NODE_VERSION: v1.31.6
        kind_v1_32_3:
          KIND_NODE_VERSION: v1.32.3
    steps:
      - task: GoTool@0
        inputs:
          version: "1.24.6"
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          APPLICATION_CLIENT_ID: $(APPLICATION_CLIENT_ID)
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          KEYVAULT_URL: $(KEYVAULT_URL)
          KEYVAULT_SECRET_NAME: $(KEYVAULT_SECRET_NAME)
          SERVICE_ACCOUNT_ISSUER: $(SERVICE_ACCOUNT_ISSUER)
          SERVICE_ACCOUNT_KEYVAULT_NAME: $(SERVICE_ACCOUNT_KEYVAULT_NAME)
      - template: templates/publish-logs.yaml
