trigger: none

pr:
  branches:
    include:
      - main

pool: Upstream Pool

jobs:
  - job: lint
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make lint
        displayName: Run lint
  - job: unit_test
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make test
        displayName: Unit test
  - job: shellcheck
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make shellcheck
        displayName: shellcheck
  - job:
    timeoutInMinutes: 20
    dependsOn:
    - unit_test
    - lint
    - shellcheck
    workspace:
      clean: all
    strategy:
      matrix:
        aks_linux:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
          # we can enable actual tenant id for functional e2e
          AZURE_TENANT_ID: "fake tenant id"
        kind_v1_19_7:
          KIND_NODE_VERSION: v1.19.7
          LOCAL_ONLY: "true"
          AZURE_TENANT_ID: "fake tenant id"
        kind_v1_20_2:
          KIND_NODE_VERSION: v1.20.2
          LOCAL_ONLY: "true"
          AZURE_TENANT_ID: "fake tenant id"
    steps:
      - script: make test-e2e
        displayName: Webhook E2E test suite
