trigger: none

pr:
  branches:
    include:
      - main

pool: staging-pool

jobs:
  - job: scan_images
    timeoutInMinutes: 10
    workspace:
      clean: all
    steps:
      - template: templates/publish-images.yaml
        parameters:
          publish: false
  - job: lint
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make lint
        displayName: golangci-lint
      - script: make helm-lint
        displayName: helm lint
      - script: go mod tidy && git diff --exit-code go.mod go.sum
        displayName: go mod tidy
  - job: unit_test
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make test
        displayName: Unit test
  - job: shellcheck
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make shellcheck
        displayName: shellcheck
  - job:
    timeoutInMinutes: 40
    dependsOn:
    - lint
    - scan_images
    - shellcheck
    - unit_test
    workspace:
      clean: all
    variables:
      # contains the following environment variables:
      # - AZURE_TENANT_ID
      # - KEYVAULT_NAME
      # - KEYVAULT_SECRET_NAME
      # - SERVICE_ACCOUNT_ISSUER
      # - SERVICE_ACCOUNT_KEYVAULT_NAME
      # - SERVICE_PRINCIPAL_CLIENT_ID
      - group: e2e-environment-variables
    strategy:
      matrix:
        aks_windows_dockershim:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
          WINDOWS_CLUSTER: "true"
          GINKGO_SKIP: \[KindOnly\]
        aks_windows_containerd:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
          WINDOWS_CLUSTER: "true"
          WINDOWS_CONTAINERD: "true"
          GINKGO_SKIP: \[KindOnly\]
        aks_linux:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
          GINKGO_SKIP: \[KindOnly\]
        arc:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
          ARC_CLUSTER: "true"
          GINKGO_SKIP: \[KindOnly\]
        kind_v1_18_19:
          KIND_NODE_VERSION: v1.18.19
          LOCAL_ONLY: "true"
          TEST_HELM_CHART: "true"
        kind_v1_19_11:
          KIND_NODE_VERSION: v1.19.11
          LOCAL_ONLY: "true"
          TEST_HELM_CHART: "true"
        kind_v1_20_7:
          KIND_NODE_VERSION: v1.20.7
          LOCAL_ONLY: "true"
          TEST_HELM_CHART: "true"
        kind_v1_21_2:
          KIND_NODE_VERSION: v1.21.2
          LOCAL_ONLY: "true"
          TEST_HELM_CHART: "true"
    steps:
      - script: echo "##vso[task.setvariable variable=CLUSTER_NAME]pod-managed-identity-e2e-$(openssl rand -hex 2)"
        displayName: Set CLUSTER_NAME
        condition: ne(variables.LOCAL_ONLY, 'true')
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          AZURE_TENANT_ID: $(AZURE_TENANT_ID)
          KEYVAULT_NAME: $(KEYVAULT_NAME)
          KEYVAULT_SECRET_NAME: $(KEYVAULT_SECRET_NAME)
          SERVICE_ACCOUNT_ISSUER: $(SERVICE_ACCOUNT_ISSUER)
          SERVICE_ACCOUNT_KEYVAULT_NAME: $(SERVICE_ACCOUNT_KEYVAULT_NAME)
          SERVICE_PRINCIPAL_CLIENT_ID: $(SERVICE_PRINCIPAL_CLIENT_ID)
      - script: az group delete --name "${CLUSTER_NAME}" --yes --no-wait || true
        displayName: Cleanup
        condition: ne(variables.LOCAL_ONLY, 'true')
