trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
    - docs
    - README.md

pool: staging-pool

jobs:
  - job: scan_images
    timeoutInMinutes: 30
    workspace:
      clean: all
    steps:
      - template: templates/scan-images.yaml
  - job: lint
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make lint
        displayName: golangci-lint
      - script: make helm-lint
        displayName: helm lint
      - script: |
          go mod tidy
          if ! git diff --exit-code go.mod go.sum; then
            echo "go.mod/go.sum is not up to date. Please run 'go mod tidy'"
            exit 1
          fi
        displayName: go mod tidy
      - script: |
          make manifests
          if ! git diff --exit-code manifest_staging/; then
            echo "manifest_staging/ is not up to date. Please run 'make manifests'"
            exit 1
          fi
        displayName: make manifests
  - job: unit_test
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make test
        displayName: Unit test
  - job: shellcheck
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make shellcheck
        displayName: shellcheck
  - job:
    timeoutInMinutes: 60
    dependsOn:
    - lint
    - scan_images
    - shellcheck
    - unit_test
    workspace:
      clean: all
    variables:
      AZURE_TENANT_ID: "fake tenant id"
      REGISTRY: upstreamk8sci.azurecr.io/azure-workload-identity
      GINKGO_SKIP: \[KindOnly\]
    strategy:
      matrix:
        aks_windows_dockershim:
          WINDOWS_CLUSTER: "true"
        aks_windows_containerd:
          WINDOWS_CLUSTER: "true"
          WINDOWS_CONTAINERD: "true"
        aks_linux:
          DUMMY_VAR: ""
        arc:
          ARC_CLUSTER: "true"
    steps:
      - script: echo "##vso[task.setvariable variable=CLUSTER_NAME]azwi-e2e-$(openssl rand -hex 2)"
        displayName: Set CLUSTER_NAME
      - script: make test-e2e
        displayName: Webhook E2E test suite
      - script: az group delete --name "${CLUSTER_NAME}" --yes --no-wait || true
        displayName: Cleanup
      - template: templates/publish-logs.yaml
  - template: templates/upgrade.yaml
    parameters:
      dependsOn:
        - lint
        - scan_images
        - shellcheck
        - unit_test
      matrix:
        upgrade_aks_linux:
          DUMMY_VAR: ""
