trigger: none

pr:
  branches:
    include:
      - main

pool: Upstream Pool

jobs:
  - job: unit_test
    timeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make test
        displayName: Unit test
  - job: aks_linux
    timeoutInMinutes: 20
    workspace:
      clean: all
    steps:
      - script: make test-e2e
        displayName: Webhook E2E test suite
        env:
          REGISTRY: upstreamk8sci.azurecr.io/aad-pod-managed-identity
