name: Azure Workload Identity CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # nightly
  pull_request:
    branches:
      - main
      - release-**
    paths-ignore:
      - docs/**
      - README.md

permissions:
  contents: read

jobs:
  azwi_build:
    strategy:
      fail-fast: false
      matrix:
        # TODO(aramase): add windows test env
        env: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.env }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.27"
          check-latest: true
      - name: Build azwi
        run: |
          make bin/azwi
      - name: Validate azwi commands
        run: |
          ./bin/azwi version
          ./bin/azwi -h
          ./bin/azwi serviceaccount -h
          ./bin/azwi serviceaccount create -h
          ./bin/azwi serviceaccount delete -h
          ./bin/azwi jwks -h
