name: Azure Workload Identity E2E

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # nightly
  push:
    branches:
      - main
      - release-**

permissions:
  id-token: write
  contents: read

jobs:
  azwi_build:
    strategy:
      fail-fast: false
      matrix:
        # TODO(aramase): add windows test env
        env: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.env }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: "1.25"
          check-latest: true
      - name: Build azwi
        run: |
          make bin/azwi
      - name: Validate azwi commands
        run: |
          ./bin/azwi version
          ./bin/azwi -h
          ./bin/azwi serviceaccount -h
          ./bin/azwi serviceaccount create -h
          ./bin/azwi serviceaccount delete -h
          ./bin/azwi jwks -h
