name: create_release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Cleanup disk
        run: |
          # Cleaning up unused tools based on the suggested workaround:
          # https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

          # Partial cleanup from the suggested workaround.
          # If we continue running out of space, we can remove everything listed in the workaround.
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.27"
          check-latest: true
      - name: Goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release --clean --fail-fast --timeout 150m --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
