name: create_release_pull_request
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we creating a release pull request for?'
        required: true
      based_on_branch:
        description: 'Which branch should we base the release pull request on?'
        required: true
        default: main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: validate version
        run: |
          echo "${{ github.event.inputs.release_version }}" | grep -E 'v[0-9]+\.[0-9]+\.[0-9]+(-alpha\.[0-9]+|-beta\.[0-9]+|-rc\.[0-9]+)?$'
          echo "${{ github.event.inputs.based_on_branch }}" | grep -E '^(main|release-[0-9]+\.[0-9]+)$'
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          fetch-depth: 0
          ref: "${{ github.event.inputs.based_on_branch }}"
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.27"
          check-latest: true
      - run: make release-manifest
        env:
          NEW_VERSION: "${{ github.event.inputs.release_version }}"
      - run: make promote-staging-manifest
      - name: Create release pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "release: update manifest and helm charts for ${{ github.event.inputs.release_version }}"
          title: "release: update manifest and helm charts for ${{ github.event.inputs.release_version }}"
          branch: "release-${{ github.event.inputs.release_version }}"
          base: ${{ github.event.inputs.based_on_branch }}
