name: create_tag
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release-**
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'update manifest and helm charts')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.6"
      - id: get-tag
        name: Get tag
        run: echo "::set-output name=tag::$(echo ${{ github.event.pull_request.head.ref }} | tr -d release-)"
      - name: Generate changelog
        run: |
          git tag ${{ steps.get-tag.outputs.tag }}
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@v0.15.0
          git-chglog ${{ steps.get-tag.outputs.tag }} > CHANGELOG.md
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-tag.outputs.tag }}
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "deploy/*.yaml"
