name: kind_e2e

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # nightly
  pull_request:
    branches:
      - main
      - release-**
    paths-ignore:
      - docs/**
      - README.md

permissions:
  id-token: write
  contents: read

jobs:
  kind-e2e:
    environment: kind-e2e
    strategy:
      fail-fast: false
      matrix:
        KIND_NODE_VERSION: [v1.19.11,v1.20.7,v1.21.2,v1.22.2]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Install Azure CLI beta
        run: |
          cd ../..
          CWD="$(pwd)"
          python3 -m venv oidc-venv
          . oidc-venv/bin/activate
          echo "activated environment"
          python3 -m pip install --upgrade pip
          echo "started installing cli beta"
          pip install -q --extra-index-url https://azcliprod.blob.core.windows.net/beta/simple/ azure-cli
          echo "installed cli beta"
          echo "$CWD/oidc-venv/bin" >> $GITHUB_PATH
      - uses: azure/login@v1.4.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - run: make test-e2e
        env:
          KIND_NODE_VERSION: ${{ matrix.KIND_NODE_VERSION }}
          LOCAL_ONLY: true
          TEST_HELM_CHART: true
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          KEYVAULT_NAME: ${{ secrets.KEYVAULT_NAME }}
          KEYVAULT_SECRET_NAME: ${{ secrets.KEYVAULT_SECRET_NAME }}
          SERVICE_ACCOUNT_ISSUER: ${{ secrets.SERVICE_ACCOUNT_ISSUER }}
          SERVICE_ACCOUNT_KEYVAULT_NAME: ${{ secrets.KEYVAULT_NAME }}
      - name: Publish logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: kind-e2e-${{ matrix.KIND_NODE_VERSION }}
          path: _artifacts/**
