name: Check Markdown links

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * *' # nightly

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
      with:
        # this will only show errors in the output
        use-quiet-mode: 'yes'
        # this will show detailed HTTP status for checked links
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/markdown.links.config.json'
